function [Depth, Z, M1A, M1P, O1A, O1P, O2A, O2P, O3A, O3P, O4A, O4P] = readApproach(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [DEPTH, Z, M0A, M0P, M1A, M1P, M2A, M2P, M3A, M3P, M4A, M4P, M5A,
%  M5P, O0A, O0P, O1A, O1P, O2A, O2P, O3A, O3P, O4A, O4P, O5A, O5P,
%  VARNAME30] = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as column vectors.
%
%  [DEPTH, Z, M0A, M0P, M1A, M1P, M2A, M2P, M3A, M3P, M4A, M4P, M5A,
%  M5P, O0A, O0P, O1A, O1P, O2A, O2P, O3A, O3P, O4A, O4P, O5A, O5P,
%  VARNAME30] = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  [Depth, Z, M0A, M0P, M1A, M1P, M2A, M2P, M3A, M3P, M4A, M4P, M5A, M5P, O0A, O0P, O1A, O1P, O2A, O2P, O3A, O3P, O4A, O4P, O5A, O5P, VarName30] = importfile("E:\OneDrive - Budapesti Mûszaki és Gazdaságtudományi Egyetem\NearFieldMeasurements\C60onAuTest\2020-10-09 1116\2020-10-09 151129 PH AC C60narrowmapat1420newnew\2020-10-09 151129 PH AC C60narrowmapat1420newnew.txt", [28, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Oct-2020 16:12:21

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [28, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 30);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Depth", "Z", "M0A", "M0P", "M1A", "M1P", "M2A", "M2P", "M3A", "M3P", "M4A", "M4P", "M5A", "M5P", "O0A", "O0P", "O1A", "O1P", "O2A", "O2P", "O3A", "O3P", "O4A", "O4P", "O5A", "O5P", "VarName30"];
opts.SelectedVariableNames = ["Depth", "Z", "M0A", "M0P", "M1A", "M1P", "M2A", "M2P", "M3A", "M3P", "M4A", "M4P", "M5A", "M5P", "O0A", "O0P", "O1A", "O1P", "O2A", "O2P", "O3A", "O3P", "O4A", "O4P", "O5A", "O5P", "VarName30"];
opts.VariableTypes = ["string", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, [1, 2, 3, 30], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 30], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Depth = tbl.Depth;
Z = tbl.Z;
M1A = tbl.M1A;
M1P = tbl.M1P;

O1A = tbl.O1A;
O1P = tbl.O1P;
O2A = tbl.O2A;
O2P = tbl.O2P;
O3A = tbl.O3A;
O3P = tbl.O3P;
O4A = tbl.O4A;
O4P = tbl.O4P;
end